server:
  port: 5555
spring:
  application:
    name: zuulsvr
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
zuul:
  routes:
    organizationservice: organization/**
    licensingservice: licensing/**
  ignored-services: '*'
  prefix: /api
